Main:
    HttpPort: 8082
    HttpsOn: false
    Domain: ""
    HttpsPort: 443
    PubDir: "static"
    ViewDir: "view/default"
    Youdb: "mydata.db"
    CookieSecure: false
    CookieHttpOnly: true
    OldSiteDomain: ""
    TLSCrtFile: ""
    TLSKeyFile: ""
Site:
    Name: "从零到壹"
    Desc: "全栈开发，前端开发，后端开发，技术，产品，赚钱，读书，电影，音乐"
    AdminEmail: "cmm@bingyan.net"
    MainDomain: "http://127.0.0.1:8082"
    MainNodeIds: "1,2,3,4,5,6,7,8,9,10"
    TimeZone: 8
    HomeShowNum: 20
    PageShowNum: 20
    TagShowNum: 20
    CategoryShowNum: 20
    TitleMaxLen: 180
    ContentMaxLen: 9000
    PostInterval: 60
    CommentListNum: 10
    CommentInterval: 20
    Authorized: false
    RegReview: false
    CloseReg: false
    AutoDataBackup: false
    AutoGetTag: true
    GetTagApi: "http://youbbs.sinaapp.com/fencigoapi.php"
    QQClientID: 0
    QQClientSecret: ""
    WeiboClientID: 0
    WeiboClientSecret: ""
    UploadSuffix: ""
    UploadImgOnly: true
    UploadImgResize: true
    UploadMaxSize: 10
    QiniuAccessKey: ""
    QiniuSecretKey: ""
    QiniuDomain: ""
    QiniuBucket: ""
    UpyunDomain: ""
    UpyunBucket: ""
    UpyunUser: ""
    UpyunPw: ""
